#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

dir=$(pwd)
bold=$(tput bold)
normal=$(tput sgr0)

git_dirs=$(find "$dir" -mindepth 2 -type d -name .git)

for git_dir in $git_dirs; do
  echo "${bold}$git_dir${normal}"

  git -C "$git_dir" branch

  echo
done
