#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dir=$(cd $(dirname "${BASH_SOURCE[0]}")/../ && pwd)
bold=$(tput bold)
normal=$(tput sgr0)

# ereolen
if [ -e $dir/ereolen/web ]; then
	git -C $dir/ereolen/web status
fi
if [ -e $dir/ereolen/web/sites/all/modules/ereol ]; then
	git -C $dir/ereolen/web/sites/all/modules/ereol status
fi

# ereolengo
if [ -e $dir/ereolengo/web ]; then
	git -C $dir/ereolengo/web status
fi
if [ -e $dir/ereolengo/web/sites/all/modules/breol ]; then
	git -C $dir/ereolengo/web/sites/all/modules/breol status
fi
