#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

"$script_dir"/symfony-php-context '../vendor/bin/phpcbf' --standard=Drupal --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md,yml' "$@"
