#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
bold=$(tput bold)
normal=$(tput sgr0)

export PATH="$script_dir/homebrew/bin:$PATH" && symfony "$@"
