#!/usr/bin/env bash
IFS=$'\n\t'

dir=$(cd $(dirname "${BASH_SOURCE[0]}")/../ && pwd)

# ereolen
rm -r $dir/ereolen/web/.docker $dir/ereolen/web/docker-compose.yml 2> /dev/null

# ereolengo
rm -r $dir/ereolengo/web/.docker $dir/ereolengo/web/docker-compose.yml 2> /dev/null
