#!/usr/bin/env bash

# ddev drush --yes pm-enable ereol_base
ddev drush --yes updatedb
ddev drush --yes features-revert-all
ddev drush --yes cache-clear all
ddev drush --yes pm-disable ding_webtrekk
# ddev drush --yes pm-disable varnish
